
CREATE TABLE rentals (
id SERIAL PRIMARY KEY,
user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
rented_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
due_date TIMESTAMP NOT NULL,
returned_at TIMESTAMP,
reminder_sent BOOLEAN
);